server:
  port: ${PORT:8080}

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: '*'
            allowedMethods:
              - '*'
            allowedHeaders:
              - '*'
      routes:
        # =====================================
        - id: sso
          uri: lb://sso-service
          predicates:
            - Path=/sso-service/**
        # =====================================
        - id: bdu
          uri: lb://bdu-service
          predicates:
            - Path=/bdu-service/**
        # =====================================
        - id: crm
          uri: lb://crm-service
          predicates:
            - Path=/crm-service/**
        # =====================================
        - id: notification
          uri: lb://notification-service
          predicates:
            - Path=/notification-service/**
        # =====================================
        - id: comment
          uri: lb://comment-service
          predicates:
            - Path=/comment-service/**
        # =====================================
        - id: statistics
          uri: lb://statistics-service
          predicates:
            - Path=/statistics-service/**
        # =====================================
        - id: task
          uri: lb://task-service
          predicates:
            - Path=/task-service/**
        # =====================================
        - id: elearning
          uri: lb://elearning-service
          predicates:
            - Path=/elearning-service/**
        # =====================================
        - id: storage
          uri: lb://storage-service
          predicates:
            - Path=/storage-service/**
        # =====================================
        - id: cart
          uri: lb://cart-service
          filters:
            - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
          predicates:
            - Path=/cart-service/**
